### PR TITLE
oui-ui-core: add typescript support

### PR DESCRIPTION
**Pull request by judecumt**
Add typescript support.
OUI's $oui $timer $md5 api typedefs are in oui-ui-core/oui_types.
App wants to use these typedefs should
1. Add `"@types/oui": "../../../oui-ui-core/htdoc/oui_types"` to devDependencies in its own package.json.
2. Add tsconfig.json and declare @vue/runtime-core somewhere.
3. See oui-app-layout for example.

### CODE REVIEW

**Comment by zhaojh329** [comment]
I personally don't think TS is very suitable for OUI's packaging method - where each page is independently packaged and not dependent on each other.

**Comment by zhaojh329** [comment]
This is also why every page of OUI is packaged in the form of a library.

**Comment by judecumt** [comment]
For now, let's have TS just for oui-ui-core's apis, since they are common to all apps, I think it will be useful for app's developer.

**Comment by judecumt** [comment]
TS is just an option, not mandatory。

**Pull request closed without merging**
